// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJCHEWpaQplSoDGa2lGtjbv8HL0YAaiFQ',
    appId: '1:172480179820:web:523fb0ad2773db73783249',
    messagingSenderId: '172480179820',
    projectId: 'path1-703bf',
    authDomain: 'path1-703bf.firebaseapp.com',
    storageBucket: 'path1-703bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKOg0dkgsf4-5uUj4FRLYESysuGQhkrmE',
    appId: '1:172480179820:android:286faf8dcafabbbf783249',
    messagingSenderId: '172480179820',
    projectId: 'path1-703bf',
    storageBucket: 'path1-703bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2CTD97pilxEhDjpYKiwvsESyBR1iogxs',
    appId: '1:172480179820:ios:055f446108a0d061783249',
    messagingSenderId: '172480179820',
    projectId: 'path1-703bf',
    storageBucket: 'path1-703bf.appspot.com',
    iosClientId: '172480179820-9dj8nkcft6m7rtin3ankcb6pb1egbch5.apps.googleusercontent.com',
    iosBundleId: 'com.example.path1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2CTD97pilxEhDjpYKiwvsESyBR1iogxs',
    appId: '1:172480179820:ios:055f446108a0d061783249',
    messagingSenderId: '172480179820',
    projectId: 'path1-703bf',
    storageBucket: 'path1-703bf.appspot.com',
    iosClientId: '172480179820-9dj8nkcft6m7rtin3ankcb6pb1egbch5.apps.googleusercontent.com',
    iosBundleId: 'com.example.path1',
  );
}
